// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: book.proto

package proto

import (
	author "github.com/cylixlee/protobuf-playground/internal/proto/author"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Book request containing the title and price of the book to buy.
type BookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Price         int32                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Author        *author.Author         `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookRequest) Reset() {
	*x = BookRequest{}
	mi := &file_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRequest) ProtoMessage() {}

func (x *BookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRequest.ProtoReflect.Descriptor instead.
func (*BookRequest) Descriptor() ([]byte, []int) {
	return file_book_proto_rawDescGZIP(), []int{0}
}

func (x *BookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BookRequest) GetAuthor() *author.Author {
	if x != nil {
		return x.Author
	}
	return nil
}

// Book response containing server reply.
type BookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookResponse) Reset() {
	*x = BookResponse{}
	mi := &file_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookResponse) ProtoMessage() {}

func (x *BookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookResponse.ProtoReflect.Descriptor instead.
func (*BookResponse) Descriptor() ([]byte, []int) {
	return file_book_proto_rawDescGZIP(), []int{1}
}

func (x *BookResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_book_proto protoreflect.FileDescriptor

const file_book_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"book.proto\x12\x05proto\x1a\vhello.proto\x1a\x13author/author.proto\"a\n" +
	"\vBookRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x05R\x05price\x12&\n" +
	"\x06author\x18\x03 \x01(\v2\x0e.author.AuthorR\x06author\"$\n" +
	"\fBookResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply2n\n" +
	"\x04Book\x124\n" +
	"\x05Hello\x12\x13.proto.HelloRequest\x1a\x14.proto.HelloResponse\"\x00\x120\n" +
	"\x03Buy\x12\x12.proto.BookRequest\x1a\x13.proto.BookResponse\"\x00B8Z6github.com/cylixlee/protobuf-playground/internal/protob\x06proto3"

var (
	file_book_proto_rawDescOnce sync.Once
	file_book_proto_rawDescData []byte
)

func file_book_proto_rawDescGZIP() []byte {
	file_book_proto_rawDescOnce.Do(func() {
		file_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_proto_rawDesc), len(file_book_proto_rawDesc)))
	})
	return file_book_proto_rawDescData
}

var file_book_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_book_proto_goTypes = []any{
	(*BookRequest)(nil),   // 0: proto.BookRequest
	(*BookResponse)(nil),  // 1: proto.BookResponse
	(*author.Author)(nil), // 2: author.Author
	(*HelloRequest)(nil),  // 3: proto.HelloRequest
	(*HelloResponse)(nil), // 4: proto.HelloResponse
}
var file_book_proto_depIdxs = []int32{
	2, // 0: proto.BookRequest.author:type_name -> author.Author
	3, // 1: proto.Book.Hello:input_type -> proto.HelloRequest
	0, // 2: proto.Book.Buy:input_type -> proto.BookRequest
	4, // 3: proto.Book.Hello:output_type -> proto.HelloResponse
	1, // 4: proto.Book.Buy:output_type -> proto.BookResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_book_proto_init() }
func file_book_proto_init() {
	if File_book_proto != nil {
		return
	}
	file_hello_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_proto_rawDesc), len(file_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_proto_goTypes,
		DependencyIndexes: file_book_proto_depIdxs,
		MessageInfos:      file_book_proto_msgTypes,
	}.Build()
	File_book_proto = out.File
	file_book_proto_goTypes = nil
	file_book_proto_depIdxs = nil
}
