# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  PORT: 11451

tasks:
  proto:
    desc: Compile Protobuf/gRPC into stub code.
    cmds:
      - task: proto-go
    silent: true

  server:
    desc: Start the gRPC server
    env:
      PP_SERVER_PORT: "{{.PORT}}"
    cmds:
      - go run ./cmd/server
    interactive: true
    silent: true

  client:
    desc: Run the gRPC client
    env:
      PP_SERVER_PORT: "{{.PORT}}"
    cmds:
      - go run ./cmd/client
    interactive: true
    silent: true

  proto-go:
    desc: Compile Protobuf/gRPC into Go stub code.
    internal: true
    shopt:
      - globstar
    cmds:
      - mkdir -p internal
      - |
        protoc -Iproto --go_out=.                                          \
               --go_opt=module=github.com/cylixlee/protobuf-playground      \
               --go-grpc_out=.                                             \
               --go-grpc_opt=module=github.com/cylixlee/protobuf-playground \
        proto/**/*.proto
    silent: true
