# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

env:
  PLAYGROUND_PORT: 11451

vars:
  DEFAULT_REQUEST_CONTENT: CYLIX
  CONTAINER_ENGINE:
    sh: |
      if command -v docker > /dev/null 2>&1; then
        echo "docker"
      elif command -v podman > /dev/null 2>&1; then
        echo "podman"
      else
        exit 1 # No supported container engine found
      fi
  SHOULD_START_PODMAN:
    sh: |
      # {{now}}
      if command -v podman > /dev/null 2>&1; then
        info="$(podman machine info)"
        info="${info##*machinestate:}"
        info="${info%%numberofmachines*}"
        case "$info" in
          *Running*)
            echo "no"
            exit 0
            ;;
        esac
        echo "yes"
      fi

tasks:
  up:
    desc: Pull up all containers needed
    deps:
      - start-podman
    cmds:
      - task: consul-up

  down:
    desc: Shut down all containers needed
    cmds:
      - task: consul-down

  server:
    desc: Start the gRPC server
    deps:
      - proto
      - up
    cmds:
      - go run ./cmd/server
    interactive: true
    silent: true

  request:*:
    desc: Request gRPC server with given content
    cmds:
      - go run ./cmd/client {{index .MATCH 0}}
    interactive: true
    silent: true

  request:
    desc: Request gRPC server with the default content
    cmds:
      - task: request:{{.DEFAULT_REQUEST_CONTENT}}
    silent: true

  proto:
    desc: Compile Protobuf/gRPC into stub code.
    internal: true
    shopt:
      - globstar
    sources:
      - proto/**/*.proto
    generates:
      - internal/proto/**/*.go
    cmds:
      - echo "Recompiling protobuf..."
      - mkdir -p internal
      - |
        protoc -Iproto                                                      \
               --go_out=.                                                   \
               --go_opt=module=github.com/cylixlee/protobuf-playground      \
               --go-grpc_out=.                                              \
               --go-grpc_opt=module=github.com/cylixlee/protobuf-playground \
        proto/**/*.proto
    silent: true

  start-podman:
    desc: Start podman if not running
    internal: true
    if: test "{{.SHOULD_START_PODMAN}}" = "yes"
    cmd: podman machine start
    silent: true

  consul-up:
    desc: Compose consul up in container engine
    internal: true
    dir: "{{.ROOT_DIR}}/consul"
    cmd: "{{.CONTAINER_ENGINE}} compose up -d 2> /dev/null"
    silent: true

  consul-down:
    desc: Compose consul down in container engine
    internal: true
    dir: "{{.ROOT_DIR}}/consul"
    cmd: "{{.CONTAINER_ENGINE}} compose down 2> /dev/null"
    silent: true
